### ISSUE TITLE
Docker源变更（Docker CE）

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/mirrorrequest#106]
Docker变更了发布方式，版本变成CE和EE，新版本号命名规则类似ubuntu。官网仓库也发生了较大变化，目前托管到了Amazon S3。无法使用[lftpsync](https://github.com/ustclug/ustcmirror-images/tree/master/lftpsync)，估计需要借助apt-mirror和reposync做镜像。

refer: https://github.com/tuna/issues/issues/207

**Comment by knight42** [comment]
http://mirrors.ustc.edu.cn/docker-ce/

**Comment by gaoyifan** [comment]
TODO:
- [ ] Fedora
- [ ] CentOS

**Comment by zhsj** [comment]
今天我看了下 https://download.docker.com/linux/，似乎能用 lftp 啊

**Comment by gaoyifan** [comment]
应该是近期刚换的。之前目录是S3的XML页面。

**Comment by gaoyifan** [comment]
目前“HTTP Server”依然是AmazonS3，我猜可能是写了个Lambda function用于生成index。

**Comment by knight42** [comment]
已使用 lftp 同步

**Comment by zhsj** [comment]
docker-apt, docker-yum 可以废弃了吧

**Comment by zhsj** [comment]
[ ] docker for windows
[ ] docker for mac
[ ] docker toolbox

似乎都不是很好镜像，只能在网站上找到链接。。。

* https://download.docker.com/win/stable/InstallDocker.msi
* https://download.docker.com/win/edge/InstallDocker.msi
* https://download.docker.com/mac/stable/Docker.dmg
* https://download.docker.com/mac/edge/Docker.dmg
* https://download.docker.com/mac/stable/DockerToolbox.pkg
* https://download.docker.com/win/stable/DockerToolbox.exe

**Comment by zhsj** [comment]
给上面几个链接做个 proxy 吧。。。。

**Comment by gaoyifan** [comment]
docker-apt, docker-yum 官方还在更新，先留着吧。

**Comment by bigeagle** [comment]
lftp 并不能镜像，目录的 href 里没有已 `/` 结尾，识别不出来。
于是手撸了脚本，已完成一轮同步。

https://github.com/tuna/tunasync-scripts/blob/master/helpers/docker-ce-filelist.py
https://github.com/tuna/tunasync-scripts/blob/master/docker-ce.sh

**Comment by zhsj** [comment]
@bigeagle lftp不能吗？感觉我们一直是lftp在同步的。。。
cc @knight42 确认下

另外 https://download.docker.com/ 上面有 win 和 mac 的目录了，我们是不是可以加上去？ @knight42

**Comment by gaoyifan** [comment]
@zhsj  我好奇的是mirrors同步这块是谁在负责？ 感觉现在处于无人管理的状态.....

**Comment by zhsj** [comment]
@gaoyifan 谁有空谁上（逃

**Comment by bigeagle** [comment]
我昨天看着能列目录直接先上的lftp然后被打脸……

**Comment by knight42** [comment]
@zhsj win 跟 mac 都已经加上了:
* http://mirrors.ustc.edu.cn/docker-ce/mac/
* http://mirrors.ustc.edu.cn/docker-ce/win/

@bigeagle 我们现在依然是在用 lftp 同步的...

**Comment by bigeagle** [comment]
woc 难道 lftp 版本不同……

**Comment by gaoyifan** [comment]
@bigeagle  @knight42  
不是因为版本不同，lftp虽然返回值为0，但实际上没有做任何同步就退出了。但我们这边的监控识别到返回值为0，认为同步成功了。

**Comment by knight42** [comment]
@gaoyifan 日志里没内容是因为没有文件更新。你可以看看以往的同步日志：

```
result.log.9.gz:
        Size: 82.00B
        LastMod: 2017-08-15 04:06:47
result.log.8.gz:
        Size: 82.00B
        LastMod: 2017-08-16 04:06:08
result.log.7.gz:
        Size: 82.00B
        LastMod: 2017-08-18 04:06:45
result.log.6.gz:
        Size: 11.62K
        LastMod: 2017-08-19 04:07:36
result.log.5.gz:
        Size: 19.99K
        LastMod: 2017-08-20 04:06:10
result.log.4.gz:
        Size: 82.00B
        LastMod: 2017-08-21 04:06:00
result.log.3.gz:
        Size: 82.00B
        LastMod: 2017-08-22 04:06:05
result.log.2.gz:
        Size: 82.00B
        LastMod: 2017-08-23 00:00:00
result.log.0:
        Size: 125.00B
        LastMod: 2017-08-23 04:06:00
result.log.1.gz:
        Size: 1.31K
        LastMod: 2017-08-23 04:06:00
```
